import { apiRequest, setAccessToken, unwrapData, unwrapList } from "./client";
import { endpoints } from "./endpoints";
import { asRecord, mapCampaign, mapChallenge, mapDialog, mapNotification, mapStory, mapUser, mapWallet } from "./mappers";
import type { AuthResult, CampaignView, ChallengeView, ContentDraft, ContentType, DialogView, LoginPayload, NotificationView, PageResult, RegisterPayload, StoryView, UnknownRecord, UserView, WalletView } from "./types";
function page<T>(payload: unknown, mapper: (row: unknown) => T): PageResult<T> { const result = unwrapList(payload); return { items: result.rows.map(mapper), total: result.total, nextPage: result.nextPage, nextCursor: result.nextCursor }; }
function query(path: string, params?: Record<string, string | number | boolean | undefined>): string { if (!params) return path; const url = new URL(path, "https://deels.local"); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== "") url.searchParams.set(key, String(value)); }); return `${url.pathname}${url.search}`; }
function contentBody(draft: ContentDraft): FormData { const data = new FormData(); data.set("title", draft.title); data.set("description", draft.description); data.set("category", draft.category); if (draft.goal !== undefined) data.set("goal", String(draft.goal)); if (draft.prize !== undefined) data.set("prize", String(draft.prize)); if (draft.endsAt) data.set("ends_at", draft.endsAt); if (draft.rules) data.set("rules", draft.rules); if (draft.media) data.set("media", draft.media); draft.documents?.forEach((file) => data.append("documents[]", file)); return data; }
function authResult(payload: unknown): AuthResult { const data = asRecord(unwrapData<unknown>(payload)); const user = mapUser(data.user ?? data.profile ?? data); const accessToken = typeof (data.access_token ?? data.token) === "string" ? String(data.access_token ?? data.token) : undefined; if (accessToken) setAccessToken(accessToken); return { user, accessToken }; }
export const deelsApi = Object.freeze({
  auth: { login: async (payload: LoginPayload) => authResult(await apiRequest(endpoints.auth.login, { method: "POST", body: payload })), register: async (payload: RegisterPayload) => authResult(await apiRequest(endpoints.auth.register, { method: "POST", body: { ...payload, password_confirmation: payload.passwordConfirmation } })), logout: async () => { await apiRequest(endpoints.auth.logout, { method: "POST" }); setAccessToken(); }, forgotPassword: async (email: string) => { await apiRequest(endpoints.auth.forgotPassword, { method: "POST", body: { email } }); }, me: async (): Promise<UserView> => mapUser(unwrapData(await apiRequest(endpoints.auth.me))) },
  challenges: { list: async (params?: Record<string, string | number | boolean | undefined>): Promise<PageResult<ChallengeView>> => page(await apiRequest(query(endpoints.challenges.list, params)), mapChallenge), detail: async (id: string) => mapChallenge(unwrapData(await apiRequest(endpoints.challenges.detail(id)))), create: async (draft: ContentDraft) => mapChallenge(unwrapData(await apiRequest(endpoints.challenges.create, { method: "POST", body: contentBody(draft) }))), update: async (id: string, draft: ContentDraft) => { const body = contentBody(draft); body.set("_method", "PUT"); return mapChallenge(unwrapData(await apiRequest(endpoints.challenges.update(id), { method: "POST", body }))); }, vote: async (id: string | number) => { await apiRequest(endpoints.challenges.vote(id), { method: "POST" }); } },
  stories: { list: async (params?: Record<string, string | number | boolean | undefined>): Promise<PageResult<StoryView>> => page(await apiRequest(query(endpoints.stories.list, params)), mapStory), detail: async (id: string) => mapStory(unwrapData(await apiRequest(endpoints.stories.detail(id)))), create: async (draft: ContentDraft) => mapStory(unwrapData(await apiRequest(endpoints.stories.create, { method: "POST", body: contentBody(draft) }))) },
  campaigns: { list: async (params?: Record<string, string | number | boolean | undefined>): Promise<PageResult<CampaignView>> => page(await apiRequest(query(endpoints.campaigns.list, params)), mapCampaign), detail: async (id: string) => mapCampaign(unwrapData(await apiRequest(endpoints.campaigns.detail(id)))), create: async (draft: ContentDraft) => mapCampaign(unwrapData(await apiRequest(endpoints.campaigns.create, { method: "POST", body: contentBody(draft) }))), donate: async (id: string | number, amount: number, anonymous = false): Promise<UnknownRecord> => unwrapData(await apiRequest(endpoints.campaigns.donate(id), { method: "POST", body: { amount, anonymous } })) },
  profile: { me: async (): Promise<UserView> => mapUser(unwrapData(await apiRequest(endpoints.profile.me))), update: async (payload: UnknownRecord): Promise<UserView> => mapUser(unwrapData(await apiRequest(endpoints.profile.update, { method: "PATCH", body: payload }))) },
  wallet: { summary: async (): Promise<WalletView> => mapWallet(unwrapData(await apiRequest(endpoints.wallet.summary))), withdraw: async (amount: number, paymentMethodId?: string): Promise<UnknownRecord> => unwrapData(await apiRequest(endpoints.wallet.withdraw, { method: "POST", body: { amount, payment_method_id: paymentMethodId } })) },
  messages: { dialogs: async (): Promise<PageResult<DialogView>> => page(await apiRequest(endpoints.messages.dialogs), mapDialog), send: async (id: string | number, text: string): Promise<UnknownRecord> => unwrapData(await apiRequest(endpoints.messages.send(id), { method: "POST", body: { text } })) },
  notifications: { list: async (): Promise<PageResult<NotificationView>> => page(await apiRequest(endpoints.notifications.list), mapNotification), read: async (id: string | number) => { await apiRequest(endpoints.notifications.read(id), { method: "POST" }); } },
  search: { all: async (search: string) => { const raw = asRecord(unwrapData(await apiRequest(endpoints.search(search)))); return { challenges: (Array.isArray(raw.challenges) ? raw.challenges : []).map(mapChallenge), stories: (Array.isArray(raw.stories) ? raw.stories : []).map(mapStory), campaigns: (Array.isArray(raw.campaigns) ? raw.campaigns : []).map(mapCampaign), raw }; } },
  contacts: { send: async (payload: UnknownRecord) => { await apiRequest(endpoints.contacts, { method: "POST", body: payload }); } },
  async createContent(type: ContentType, draft: ContentDraft, editingId?: string) { if (type === "challenge") return editingId ? deelsApi.challenges.update(editingId, draft) : deelsApi.challenges.create(draft); if (type === "story") return deelsApi.stories.create(draft); return deelsApi.campaigns.create(draft); },
});
